package cz.muni.fi.pv207.eduqick.jbpm_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Manager implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Manager")
   private java.lang.String manager;
   @org.kie.api.definition.type.Label(value = "E-mail")
   private java.lang.String email;

   public Manager()
   {
   }

   public java.lang.String getManager()
   {
      return this.manager;
   }

   public void setManager(java.lang.String manager)
   {
      this.manager = manager;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public Manager(java.lang.String manager, java.lang.String email)
   {
      this.manager = manager;
      this.email = email;
   }

}