package cz.muni.fi.pv207.eduqick.jbpm_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Manager implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Manager() {
    }

}